version: '3.8'

services:
  platform-back:
    build:
      context: ./platform-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  client-back:
    build:
      context: ./client-back
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge